/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID ee13)
#  Generated on:      Mon Dec 23 05:20:41 2019
#  Design:            CHIP
#  Command:           saveNetlist CHIP.v
###############################################################
*/
module LBP (
	clk, 
	rst_n, 
	in_valid, 
	in_image, 
	out_valid, 
	out_image);
   input clk;
   input rst_n;
   input in_valid;
   input [7:0] in_image;
   output out_valid;
   output [7:0] out_image;

   // Internal wires
   wire FE_OFN552_C_rst_n;
   wire FE_OCPN48_C_out_image_0;
   wire FE_RN_30;
   wire FE_OCPN46_C_out_image_6;
   wire FE_OCPN45_C_out_valid;
   wire FE_RN_28;
   wire FE_OCPN551_C_out_image_2;
   wire FE_OCPN550_C_out_image_1;
   wire FE_OCPN549_C_out_image_0;
   wire FE_OCPN548_C_out_valid;
   wire CTS_4;
   wire FE_RN_237_0;
   wire FE_RN_236_0;
   wire FE_RN_235_0;
   wire FE_RN_234_0;
   wire FE_RN_233_0;
   wire FE_OCPN42_n448;
   wire FE_OCPN41_n448;
   wire FE_RN_232_0;
   wire FE_RN_231_0;
   wire FE_RN_230_0;
   wire FE_RN_27;
   wire FE_RN_229_0;
   wire FE_RN_26;
   wire FE_RN_25;
   wire FE_RN_24;
   wire FE_RN_227_0;
   wire FE_RN_226_0;
   wire FE_RN_225_0;
   wire FE_RN_223_0;
   wire FE_RN_222_0;
   wire FE_RN_23;
   wire FE_RN_22;
   wire FE_RN_221_0;
   wire FE_OCPN35_n448;
   wire FE_RN_21;
   wire FE_RN_20;
   wire FE_RN_218_0;
   wire FE_RN_217_0;
   wire FE_RN_216_0;
   wire FE_RN_215_0;
   wire FE_RN_19;
   wire FE_RN_18;
   wire FE_RN_214_0;
   wire FE_RN_213_0;
   wire FE_RN_212_0;
   wire FE_RN_211_0;
   wire FE_RN_209_0;
   wire FE_RN_208_0;
   wire FE_RN_207_0;
   wire FE_RN_206_0;
   wire FE_RN_205_0;
   wire FE_RN_204_0;
   wire FE_RN_203_0;
   wire FE_RN_201_0;
   wire FE_RN_200_0;
   wire FE_RN_199_0;
   wire FE_RN_198_0;
   wire FE_RN_15;
   wire FE_RN_197_0;
   wire FE_RN_196_0;
   wire FE_RN_195_0;
   wire FE_RN_194_0;
   wire FE_RN_193_0;
   wire FE_RN_191_0;
   wire FE_RN_189_0;
   wire FE_RN_188_0;
   wire FE_RN_187_0;
   wire FE_RN_186_0;
   wire FE_RN_185_0;
   wire FE_RN_184_0;
   wire FE_RN_14;
   wire FE_RN_183_0;
   wire FE_RN_182_0;
   wire FE_RN_180_0;
   wire FE_RN_179_0;
   wire FE_RN_177_0;
   wire FE_RN_176_0;
   wire FE_RN_175_0;
   wire FE_RN_174_0;
   wire FE_RN_173_0;
   wire FE_RN_11;
   wire FE_RN_10;
   wire FE_RN_171_0;
   wire FE_RN_170_0;
   wire FE_RN_169_0;
   wire FE_RN_168_0;
   wire FE_RN_167_0;
   wire FE_RN_166_0;
   wire FE_RN_165_0;
   wire FE_RN_164_0;
   wire FE_RN_163_0;
   wire FE_RN_162_0;
   wire FE_RN_161_0;
   wire FE_RN_160_0;
   wire FE_RN_159_0;
   wire FE_RN_158_0;
   wire FE_RN_157_0;
   wire FE_RN_156_0;
   wire FE_RN_155_0;
   wire FE_RN_154_0;
   wire FE_RN_152_0;
   wire FE_RN_151_0;
   wire FE_RN_147_0;
   wire FE_RN_146_0;
   wire FE_RN_7;
   wire FE_RN_6;
   wire FE_RN_142_0;
   wire FE_RN_141_0;
   wire FE_RN_140_0;
   wire FE_RN_139_0;
   wire FE_RN_137_0;
   wire FE_RN_136_0;
   wire FE_RN_134_0;
   wire FE_RN_133_0;
   wire FE_RN_132_0;
   wire FE_RN_131_0;
   wire FE_RN_130_0;
   wire FE_RN_129_0;
   wire FE_RN_128_0;
   wire FE_RN_127_0;
   wire FE_RN_126_0;
   wire FE_RN_5;
   wire FE_RN_122_0;
   wire FE_RN_121_0;
   wire FE_RN_120_0;
   wire FE_RN_117_0;
   wire FE_RN_116_0;
   wire FE_RN_112_0;
   wire FE_RN_111_0;
   wire FE_RN_110_0;
   wire FE_RN_109_0;
   wire FE_RN_108_0;
   wire FE_RN_107_0;
   wire FE_RN_105_0;
   wire FE_RN_104_0;
   wire FE_RN_103_0;
   wire FE_RN_102_0;
   wire FE_RN_101_0;
   wire FE_RN_100_0;
   wire FE_RN_99_0;
   wire FE_RN_98_0;
   wire FE_RN_97_0;
   wire FE_RN_96_0;
   wire FE_RN_95_0;
   wire FE_RN_94_0;
   wire FE_RN_92_0;
   wire FE_RN_91_0;
   wire FE_RN_90_0;
   wire FE_RN_89_0;
   wire FE_RN_87_0;
   wire FE_RN_83_0;
   wire FE_RN_82_0;
   wire FE_RN_81_0;
   wire FE_RN_79_0;
   wire FE_RN_78_0;
   wire FE_RN_68_0;
   wire FE_RN_67_0;
   wire FE_RN_65_0;
   wire FE_RN_61_0;
   wire FE_RN_60_0;
   wire FE_RN_59_0;
   wire FE_RN_1;
   wire FE_RN_56_0;
   wire FE_RN_54_0;
   wire FE_RN_49_0;
   wire FE_RN_43_0;
   wire FE_RN_38_0;
   wire FE_RN_33_0;
   wire FE_RN_31_0;
   wire FE_RN_28_0;
   wire FE_RN_27_0;
   wire FE_RN_26_0;
   wire FE_RN_24_0;
   wire FE_RN_23_0;
   wire FE_RN_20_0;
   wire FE_RN_16_0;
   wire FE_RN_15_0;
   wire FE_RN_12_0;
   wire FE_RN_11_0;
   wire FE_RN_5_0;
   wire FE_RN_4_0;
   wire FE_RN_2_0;
   wire FE_OFN6_n204;
   wire FE_OFN0_C_rst_n;
   wire finish_all;
   wire N170;
   wire N171;
   wire N172;
   wire N212;
   wire N213;
   wire N214;
   wire N215;
   wire N216;
   wire N217;
   wire N218;
   wire N219;
   wire N220;
   wire N221;
   wire N222;
   wire N223;
   wire write_en;
   wire N226;
   wire N227;
   wire N228;
   wire N229;
   wire N230;
   wire N231;
   wire N232;
   wire N233;
   wire N1887;
   wire N1888;
   wire N1889;
   wire N1890;
   wire N1891;
   wire N1892;
   wire N1893;
   wire N1894;
   wire N1895;
   wire N1896;
   wire N1897;
   wire N1898;
   wire N1899;
   wire N1900;
   wire N1901;
   wire N1902;
   wire N1903;
   wire N1904;
   wire N1905;
   wire N1906;
   wire N1907;
   wire N1908;
   wire N1909;
   wire N1910;
   wire N1911;
   wire N1912;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire C1_DATA6_4;
   wire C1_DATA6_3;
   wire C1_DATA6_2;
   wire C1_DATA6_1;
   wire C1_DATA6_0;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n209;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n226;
   wire n227;
   wire n228;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n292;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n305;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n328;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n338;
   wire n339;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n354;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n375;
   wire n379;
   wire n381;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n407;
   wire n409;
   wire n410;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n480;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n486;
   wire n487;
   wire n488;
   wire n489;
   wire n490;
   wire n491;
   wire n493;
   wire n494;
   wire n495;
   wire n496;
   wire n497;
   wire n498;
   wire n499;
   wire n500;
   wire n501;
   wire n502;
   wire n503;
   wire n504;
   wire n506;
   wire n507;
   wire n508;
   wire n509;
   wire n511;
   wire n512;
   wire n513;
   wire n515;
   wire n516;
   wire n517;
   wire n518;
   wire n520;
   wire n521;
   wire n522;
   wire n523;
   wire n524;
   wire n525;
   wire n526;
   wire n527;
   wire n528;
   wire n530;
   wire n531;
   wire n532;
   wire n535;
   wire n536;
   wire n538;
   wire n539;
   wire n540;
   wire n541;
   wire n542;
   wire n543;
   wire n544;
   wire n545;
   wire n546;
   wire n547;
   wire n548;
   wire [1:0] state;
   wire [1:0] next_state;
   wire [3:0] counter_block;
   wire [9:5] i;
   wire [9:0] A;
   wire [7:0] D;
   wire [7:0] center;
   wire [7:0] block;
   wire [7:0] Q;

   BUFX4 FE_OFC43_C_rst_n (.A(rst_n),
	.Y(FE_OFN552_C_rst_n));
   OAI21X1 FE_RC_484_0 (.A0(n413),
	.A1(n414),
	.B0(n439),
	.Y(n384));
   OAI21X1 FE_RC_483_0 (.A0(n413),
	.A1(n414),
	.B0(n394),
	.Y(n400));
   OAI21X1 FE_RC_482_0 (.A0(n427),
	.A1(n284),
	.B0(n356),
	.Y(n359));
   OAI21X1 FE_RC_481_0 (.A0(n413),
	.A1(n414),
	.B0(n323),
	.Y(n319));
   XNOR2X1 FE_RC_480_0 (.A(n330),
	.B(n540),
	.Y(FE_RN_232_0));
   BUFX1 FE_OCPC48_C_out_image_0 (.A(out_image[0]),
	.Y(FE_OCPN48_C_out_image_0));
   BUFX12 FE_OCPC47_C_out_image_3 (.A(FE_RN_30),
	.Y(out_image[3]));
   BUFX1 FE_OCPC46_C_out_image_6 (.A(out_image[6]),
	.Y(FE_OCPN46_C_out_image_6));
   BUFX1 FE_OCPC45_C_out_valid (.A(out_valid),
	.Y(FE_OCPN45_C_out_valid));
   BUFX8 FE_OCPC44_C_out_image_7 (.A(FE_RN_28),
	.Y(out_image[7]));
   BUFX12 FE_OCPC42_C_out_image_2 (.A(FE_OCPN551_C_out_image_2),
	.Y(out_image[2]));
   BUFX12 FE_OCPC41_C_out_image_1 (.A(FE_OCPN550_C_out_image_1),
	.Y(out_image[1]));
   BUFX12 FE_OCPC40_C_out_image_0 (.A(FE_OCPN549_C_out_image_0),
	.Y(out_image[0]));
   BUFX12 FE_OCPC39_C_out_valid (.A(FE_OCPN548_C_out_valid),
	.Y(out_valid));
   CLKBUFX12 CTS_ccl_a_BUF_clk_G0_L2_1 (.A(clk),
	.Y(CTS_4));
   AND2X1 FE_RC_479_0 (.A(FE_RN_187_0),
	.B(FE_RN_186_0),
	.Y(FE_RN_237_0));
   NAND3X1 FE_RC_478_0 (.A(FE_RN_237_0),
	.B(FE_RN_197_0),
	.C(FE_RN_193_0),
	.Y(N1893));
   AOI22X1 FE_RC_477_0 (.A0(n284),
	.A1(n393),
	.B0(n427),
	.B1(n394),
	.Y(n402));
   CLKINVX2 FE_RC_476_0 (.A(FE_RN_235_0),
	.Y(n399));
   NAND2X1 FE_RC_475_0 (.A(n420),
	.B(n398),
	.Y(FE_RN_236_0));
   OAI2BB1X1 FE_RC_474_0 (.A0N(n397),
	.A1N(FE_RN_1),
	.B0(FE_RN_236_0),
	.Y(FE_RN_235_0));
   NOR2BX1 FE_RC_473_0 (.AN(n228),
	.B(n285),
	.Y(FE_RN_233_0));
   INVX2 FE_RC_472_0 (.A(FE_RN_234_0),
	.Y(n427));
   NAND2X1 FE_RC_471_0 (.A(FE_RN_24),
	.B(FE_RN_233_0),
	.Y(FE_RN_234_0));
   BUFX1 FE_OCPC42_n448 (.A(n448),
	.Y(FE_OCPN42_n448));
   AOI22X1 FE_RC_470_0 (.A0(FE_RN_5),
	.A1(n316),
	.B0(n420),
	.B1(n317),
	.Y(n318));
   BUFX2 FE_OCPC41_n448 (.A(n448),
	.Y(FE_OCPN41_n448));
   AOI22X1 FE_RC_469_0 (.A0(FE_RN_26),
	.A1(C1_DATA6_1),
	.B0(n413),
	.B1(n350),
	.Y(n346));
   NAND3X1 FE_RC_468_0 (.A(n300),
	.B(n299),
	.C(n298),
	.Y(FE_RN_56_0));
   NAND3X1 FE_RC_467_0 (.A(n358),
	.B(n360),
	.C(n357),
	.Y(FE_RN_215_0));
   NAND3X1 FE_RC_466_0 (.A(n256),
	.B(n254),
	.C(n255),
	.Y(FE_RN_173_0));
   OAI2BB1X1 FE_RC_465_0 (.A0N(n199),
	.A1N(FE_RN_6),
	.B0(FE_RN_33_0),
	.Y(FE_RN_68_0));
   AOI2BB2X1 FE_RC_463_0 (.A0N(FE_RN_180_0),
	.A1N(FE_RN_179_0),
	.B0(FE_RN_5),
	.B1(n417),
	.Y(n421));
   OAI2BB1X1 FE_RC_461_0 (.A0N(FE_OCPN41_n448),
	.A1N(FE_RN_232_0),
	.B0(FE_RN_225_0),
	.Y(FE_RN_231_0));
   NOR2X1 FE_RC_459_0 (.A(FE_RN_231_0),
	.B(FE_RN_189_0),
	.Y(FE_RN_193_0));
   AND2X1 FE_RC_458_0 (.A(n237),
	.B(n238),
	.Y(FE_RN_230_0));
   NAND2X1 FE_RC_457_0 (.A(FE_RN_230_0),
	.B(FE_RN_10),
	.Y(FE_RN_23));
   OR2X1 FE_RC_160_0_dup (.A(n259),
	.B(n258),
	.Y(FE_RN_27));
   AOI22X1 FE_RC_456_0 (.A0(FE_RN_5),
	.A1(n292),
	.B0(n420),
	.B1(C1_DATA6_3),
	.Y(n254));
   NAND2X1 FE_RC_455_0 (.A(n497),
	.B(FE_RN_116_0),
	.Y(FE_RN_229_0));
   OAI2BB1X1 FE_RC_454_0 (.A0N(i[9]),
	.A1N(FE_RN_23),
	.B0(FE_RN_229_0),
	.Y(FE_RN_112_0));
   AND2X1 U303_dup (.A(FE_RN_24),
	.B(n244),
	.Y(FE_RN_26));
   AOI22X1 FE_RC_453_0 (.A0(FE_RN_5),
	.A1(n356),
	.B0(n420),
	.B1(C1_DATA6_0),
	.Y(n357));
   AOI22X1 FE_RC_452_0 (.A0(n427),
	.A1(n349),
	.B0(n284),
	.B1(n350),
	.Y(n351));
   NAND2X1 U343_dup (.A(FE_RN_24),
	.B(n265),
	.Y(FE_RN_25));
   OAI2BB1X1 FE_RC_451_0 (.A0N(n339),
	.A1N(n284),
	.B0(FE_RN_188_0),
	.Y(FE_RN_189_0));
   NAND2X1 FE_RC_450_0 (.A(in_valid),
	.B(n216),
	.Y(n515));
   BUFX2 FE_OCPC6_n515_dup (.A(n515),
	.Y(FE_RN_24));
   NAND4X1 FE_RC_445_0 (.A(FE_RN_147_0),
	.B(FE_RN_140_0),
	.C(FE_RN_139_0),
	.D(FE_RN_141_0),
	.Y(N1889));
   NAND2X1 FE_RC_444_0 (.A(FE_RN_24),
	.B(FE_RN_61_0),
	.Y(n283));
   NOR2BX1 FE_RC_443_0 (.AN(FE_RN_61_0),
	.B(n466),
	.Y(FE_RN_226_0));
   INVX2 FE_RC_442_0 (.A(FE_RN_227_0),
	.Y(n284));
   NAND2X1 FE_RC_441_0 (.A(FE_RN_24),
	.B(FE_RN_226_0),
	.Y(FE_RN_227_0));
   MXI2X1 FE_RC_440_0 (.S0(FE_RN_223_0),
	.B(n501),
	.A(n502),
	.Y(N170));
   OAI21X1 FE_RC_439_0 (.A0(FE_RN_25),
	.A1(n475),
	.B0(FE_RN_21),
	.Y(n476));
   NAND2X1 FE_RC_438_0 (.A(n430),
	.B(i[6]),
	.Y(FE_RN_225_0));
   CLKINVX1 FE_RC_435_0 (.A(n233),
	.Y(FE_RN_223_0));
   NAND2X1 FE_RC_433_0 (.A(n476),
	.B(out_image[1]),
	.Y(FE_RN_222_0));
   NAND2X1 FE_RC_432_0 (.A(FE_RN_120_0),
	.B(FE_RN_222_0),
	.Y(N1906));
   NAND2XL FE_RC_430_0 (.A(FE_RN_6),
	.B(A[3]),
	.Y(FE_RN_99_0));
   NAND4X1 FE_RC_429_0 (.A(n424),
	.B(FE_RN_200_0),
	.C(n423),
	.D(n421),
	.Y(n432));
   AOI2BB2X1 FE_RC_428_0 (.A0N(FE_RN_137_0),
	.A1N(FE_RN_136_0),
	.B0(n420),
	.B1(C1_DATA6_1),
	.Y(n345));
   AOI22X1 FE_RC_426_0 (.A0(n418),
	.A1(n489),
	.B0(n420),
	.B1(C1_DATA6_2),
	.Y(n297));
   NOR2X1 FE_RC_416_0_dup (.A(n204),
	.B(FE_RN_218_0),
	.Y(FE_RN_22));
   INVX2 FE_OCPC36_FE_RN_21 (.A(FE_RN_21),
	.Y(n448));
   INVX2 FE_OCPC35_FE_RN_21 (.A(FE_RN_21),
	.Y(FE_RN_191_0));
   NAND3X1 FE_RC_424_0 (.A(n347),
	.B(n346),
	.C(n345),
	.Y(FE_RN_201_0));
   NAND2X1 FE_RC_423_0 (.A(n269),
	.B(n268),
	.Y(FE_RN_221_0));
   NAND2X1 FE_RC_422_0 (.A(FE_RN_24),
	.B(FE_RN_221_0),
	.Y(n277));
   BUFX1 FE_OCPC35_n448 (.A(n448),
	.Y(FE_OCPN35_n448));
   NAND2BX1 U261_dup1 (.AN(next_state[1]),
	.B(next_state[0]),
	.Y(FE_RN_21));
   CLKINVX2 FE_OFC1_n438_dup (.A(n438),
	.Y(FE_RN_20));
   OR2X1 FE_RC_417_0 (.A(n481),
	.B(counter_block[0]),
	.Y(FE_RN_218_0));
   NAND2X1 FE_RC_415_0 (.A(FE_RN_24),
	.B(n221),
	.Y(n259));
   NOR2BX1 FE_RC_414_0 (.AN(n221),
	.B(FE_RN_206_0),
	.Y(FE_RN_216_0));
   NAND2X1 FE_RC_413_0 (.A(FE_RN_24),
	.B(FE_RN_216_0),
	.Y(FE_RN_217_0));
   NAND2X1 FE_RC_412_0 (.A(FE_RN_205_0),
	.B(FE_RN_217_0),
	.Y(FE_RN_87_0));
   CLKINVX2 FE_RC_411_0 (.A(FE_RN_215_0),
	.Y(FE_RN_129_0));
   NOR3X1 FE_RC_308_0_dup1 (.A(n204),
	.B(n481),
	.C(counter_block[0]),
	.Y(FE_RN_19));
   MXI2X1 FE_RC_105_0_dup1 (.S0(n204),
	.B(n448),
	.A(n219),
	.Y(FE_RN_18));
   NOR2X1 FE_RC_408_0 (.A(n430),
	.B(n356),
	.Y(FE_RN_214_0));
   AOI21X1 FE_RC_407_0 (.A0(FE_RN_7),
	.A1(n356),
	.B0(FE_RN_214_0),
	.Y(n361));
   OAI2BB1X1 FE_RC_405_0 (.A0N(C1_DATA6_4),
	.A1N(n420),
	.B0(FE_RN_156_0),
	.Y(FE_RN_157_0));
   NAND4X1 FE_RC_404_0 (.A(n401),
	.B(n399),
	.C(n400),
	.D(n402),
	.Y(FE_RN_146_0));
   NOR2BX1 FE_RC_402_0 (.AN(n228),
	.B(n477),
	.Y(FE_RN_212_0));
   INVX2 FE_RC_401_0 (.A(FE_RN_213_0),
	.Y(FE_RN_83_0));
   NAND2X1 FE_RC_400_0 (.A(FE_RN_24),
	.B(FE_RN_212_0),
	.Y(FE_RN_213_0));
   CLKINVX2 FE_RC_398_0 (.A(FE_RN_116_0),
	.Y(FE_RN_211_0));
   AOI2BB1X1 FE_RC_397_0 (.A0N(FE_RN_211_0),
	.A1N(n487),
	.B0(FE_RN_196_0),
	.Y(FE_RN_197_0));
   NAND2X1 FE_RC_396_0 (.A(n473),
	.B(FE_OCPN48_C_out_image_0),
	.Y(FE_RN_209_0));
   NAND2X1 FE_RC_395_0 (.A(FE_RN_126_0),
	.B(FE_RN_209_0),
	.Y(N1905));
   NOR2X1 FE_RC_393_0 (.A(FE_RN_87_0),
	.B(FE_RN_83_0),
	.Y(FE_RN_7));
   AOI21X1 FE_RC_391_0 (.A0(n435),
	.A1(FE_RN_182_0),
	.B0(n389),
	.Y(FE_RN_177_0));
   AND2X1 FE_RC_388_0 (.A(FE_RN_54_0),
	.B(n297),
	.Y(FE_RN_139_0));
   NAND2X1 FE_RC_387_0 (.A(n465),
	.B(out_image[2]),
	.Y(FE_RN_208_0));
   NAND2X1 FE_RC_386_0 (.A(FE_RN_121_0),
	.B(FE_RN_208_0),
	.Y(N1907));
   NAND2X1 FE_RC_385_0 (.A(FE_OFN6_n204),
	.B(n464),
	.Y(FE_RN_207_0));
   NAND2X1 FE_RC_384_0 (.A(FE_RN_21),
	.B(FE_RN_207_0),
	.Y(n463));
   AND2X1 FE_RC_382_0 (.A(n513),
	.B(n493),
	.Y(FE_RN_204_0));
   NAND2X1 FE_RC_381_0 (.A(FE_RN_24),
	.B(FE_RN_204_0),
	.Y(FE_RN_205_0));
   CLKINVX2 FE_RC_380_0 (.A(n257),
	.Y(FE_RN_206_0));
   NOR2X1 FE_RC_378_0 (.A(FE_RN_211_0),
	.B(FE_RN_2_0),
	.Y(FE_RN_203_0));
   NOR2X1 FE_RC_377_0 (.A(n290),
	.B(FE_RN_203_0),
	.Y(FE_RN_101_0));
   NAND2X1 FE_RC_375_0 (.A(n278),
	.B(FE_RN_27),
	.Y(n430));
   NAND4X1 FE_RC_374_0 (.A(n386),
	.B(n385),
	.C(n384),
	.D(n383),
	.Y(FE_RN_59_0));
   CLKINVX2 FE_RC_373_0 (.A(FE_RN_201_0),
	.Y(FE_RN_67_0));
   OAI21X1 FE_RC_371_0 (.A0(n414),
	.A1(n413),
	.B0(n426),
	.Y(FE_RN_200_0));
   INVX2 FE_RC_368_0 (.A(counter_block[0]),
	.Y(FE_RN_199_0));
   NOR2BX1 FE_RC_367_0 (.AN(FE_RN_199_0),
	.B(FE_RN_14),
	.Y(n548));
   OR2X1 FE_RC_366_0 (.A(FE_RN_14),
	.B(counter_block[0]),
	.Y(n501));
   NAND2X1 FE_RC_365_0 (.A(n430),
	.B(C1_DATA6_1),
	.Y(FE_RN_198_0));
   NAND2X1 FE_RC_364_0 (.A(FE_RN_198_0),
	.B(n351),
	.Y(n352));
   NAND2X1 FE_RC_228_0_dup (.A(FE_RN_122_0),
	.B(FE_RN_10),
	.Y(FE_RN_15));
   NAND4X1 FE_RC_363_0 (.A(FE_RN_67_0),
	.B(FE_RN_176_0),
	.C(FE_RN_175_0),
	.D(n348),
	.Y(N1888));
   NAND2X1 FE_RC_361_0 (.A(n435),
	.B(A[6]),
	.Y(FE_RN_186_0));
   NAND2X1 FE_RC_360_0 (.A(FE_RN_15),
	.B(i[6]),
	.Y(FE_RN_187_0));
   NAND2X1 FE_RC_359_0 (.A(n427),
	.B(n338),
	.Y(FE_RN_188_0));
   AOI22X1 FE_RC_353_0 (.A0(n420),
	.A1(n333),
	.B0(FE_RN_1),
	.B1(n339),
	.Y(FE_RN_194_0));
   OAI21X1 FE_RC_352_0 (.A0(n414),
	.A1(n413),
	.B0(n338),
	.Y(FE_RN_195_0));
   NAND2X1 FE_RC_351_0 (.A(FE_RN_195_0),
	.B(FE_RN_194_0),
	.Y(FE_RN_196_0));
   INVX2 FE_RC_348_0 (.A(FE_RN_184_0),
	.Y(n298));
   NAND2X1 FE_RC_347_0 (.A(n413),
	.B(n301),
	.Y(FE_RN_185_0));
   OAI2BB1X1 FE_RC_346_0 (.A0N(C1_DATA6_2),
	.A1N(FE_RN_26),
	.B0(FE_RN_185_0),
	.Y(FE_RN_184_0));
   NAND2X1 U338_dup1 (.A(FE_OFN6_n204),
	.B(n207),
	.Y(FE_RN_14));
   NAND3X1 FE_RC_345_0 (.A(FE_RN_95_0),
	.B(FE_OFN552_C_rst_n),
	.C(FE_RN_94_0),
	.Y(FE_RN_96_0));
   NAND2X1 FE_RC_344_0 (.A(n463),
	.B(FE_OCPN46_C_out_image_6),
	.Y(FE_RN_183_0));
   NAND2X1 FE_RC_343_0 (.A(FE_RN_132_0),
	.B(FE_RN_183_0),
	.Y(N1911));
   XOR2X1 FE_RC_342_0 (.A(n438),
	.B(C1_DATA6_0),
	.Y(N214));
   NAND3X1 FE_RC_341_0 (.A(FE_RN_49_0),
	.B(FE_RN_11_0),
	.C(FE_RN_177_0),
	.Y(N1892));
   INVX2 FE_RC_339_0 (.A(FE_RN_12_0),
	.Y(FE_RN_182_0));
   CLKINVX1 FE_RC_337_0 (.A(n419),
	.Y(FE_RN_179_0));
   CLKINVX2 FE_RC_336_0 (.A(n420),
	.Y(FE_RN_180_0));
   NAND2X1 FE_RC_334_0 (.A(n237),
	.B(n238),
	.Y(FE_RN_31_0));
   NAND3X1 FE_RC_329_0 (.A(FE_RN_107_0),
	.B(FE_RN_174_0),
	.C(FE_RN_105_0),
	.Y(N1895));
   CLKINVX2 FE_RC_328_0 (.A(FE_RN_68_0),
	.Y(FE_RN_175_0));
   CLKINVX2 FE_RC_327_0 (.A(n352),
	.Y(FE_RN_176_0));
   NOR2X1 FE_RC_325_0 (.A(n431),
	.B(FE_RN_16_0),
	.Y(FE_RN_174_0));
   OAI21X1 FE_RC_323_0 (.A0(FE_RN_25),
	.A1(n483),
	.B0(FE_RN_21),
	.Y(n484));
   OAI21X1 FE_RC_321_0 (.A0(FE_RN_25),
	.A1(n493),
	.B0(FE_RN_21),
	.Y(n494));
   CLKINVX2 FE_RC_319_0 (.A(FE_RN_173_0),
	.Y(FE_RN_100_0));
   OAI22X1 FE_RC_316_0 (.A0(FE_RN_20),
	.A1(n480),
	.B0(FE_RN_134_0),
	.B1(FE_RN_133_0),
	.Y(N1912));
   NAND2X1 U333_dup (.A(n438),
	.B(C1_DATA6_0),
	.Y(FE_RN_11));
   OR2X1 FE_RC_54_0_dup (.A(n283),
	.B(n474),
	.Y(FE_RN_10));
   CLKINVXL FE_RC_312_0 (.A(out_image[5]),
	.Y(FE_RN_170_0));
   NAND2BX1 FE_RC_311_0 (.AN(FE_RN_170_0),
	.B(n470),
	.Y(FE_RN_171_0));
   OAI21XL FE_RC_310_0 (.A0(n495),
	.A1(n471),
	.B0(FE_RN_171_0),
	.Y(N1910));
   NOR3X1 FE_RC_308_0 (.A(n204),
	.B(n481),
	.C(counter_block[0]),
	.Y(n482));
   NAND2X1 FE_RC_307_0 (.A(FE_RN_5),
	.B(n445),
	.Y(FE_RN_156_0));
   NAND2X1 FE_RC_305_0 (.A(n413),
	.B(n375),
	.Y(FE_RN_158_0));
   OAI2BB1X1 FE_RC_304_0 (.A0N(C1_DATA6_4),
	.A1N(FE_RN_26),
	.B0(FE_RN_158_0),
	.Y(FE_RN_159_0));
   NOR2X1 FE_RC_303_0 (.A(FE_RN_159_0),
	.B(FE_RN_157_0),
	.Y(FE_RN_160_0));
   NAND2X1 FE_RC_302_0 (.A(FE_RN_18),
	.B(A[4]),
	.Y(FE_RN_161_0));
   AOI22X1 FE_RC_301_0 (.A0(FE_RN_116_0),
	.A1(n445),
	.B0(FE_RN_23),
	.B1(n375),
	.Y(FE_RN_162_0));
   NAND2X1 FE_RC_300_0 (.A(n284),
	.B(n375),
	.Y(FE_RN_163_0));
   NAND2X1 FE_RC_299_0 (.A(n427),
	.B(n445),
	.Y(FE_RN_164_0));
   NAND2X1 FE_RC_298_0 (.A(FE_RN_164_0),
	.B(FE_RN_163_0),
	.Y(FE_RN_165_0));
   INVX2 FE_RC_297_0 (.A(FE_RN_20_0),
	.Y(FE_RN_166_0));
   NAND2BX1 FE_RC_296_0 (.AN(FE_RN_21),
	.B(FE_RN_166_0),
	.Y(FE_RN_167_0));
   OAI2BB1X1 FE_RC_295_0 (.A0N(C1_DATA6_4),
	.A1N(n430),
	.B0(FE_RN_167_0),
	.Y(FE_RN_168_0));
   NOR2X1 FE_RC_294_0 (.A(FE_RN_168_0),
	.B(FE_RN_165_0),
	.Y(FE_RN_169_0));
   NAND4X1 FE_RC_293_0 (.A(FE_RN_169_0),
	.B(FE_RN_162_0),
	.C(FE_RN_161_0),
	.D(FE_RN_160_0),
	.Y(N1891));
   CLKINVX2 FE_RC_292_0 (.A(FE_RN_154_0),
	.Y(n288));
   NAND2X1 FE_RC_291_0 (.A(n284),
	.B(n287),
	.Y(FE_RN_155_0));
   OAI2BB1X1 FE_RC_290_0 (.A0N(n292),
	.A1N(n427),
	.B0(FE_RN_155_0),
	.Y(FE_RN_154_0));
   MXI2X1 FE_RC_288_0 (.S0(n444),
	.B(n503),
	.A(n504),
	.Y(N215));
   INVX2 FE_RC_286_0 (.A(FE_RN_152_0),
	.Y(n420));
   INVX2 FE_RC_285_0 (.A(n251),
	.Y(FE_RN_151_0));
   NAND2BX1 FE_RC_284_0 (.AN(FE_RN_151_0),
	.B(FE_RN_24),
	.Y(FE_RN_152_0));
   OAI21X1 FE_RC_282_0 (.A0(n420),
	.A1(FE_RN_1),
	.B0(n439),
	.Y(n383));
   CLKINVX2 FE_RC_272_0 (.A(FE_RN_56_0),
	.Y(FE_RN_147_0));
   CLKINVX2 FE_RC_270_0 (.A(FE_RN_146_0),
	.Y(FE_RN_142_0));
   INVX2 FE_OCPC22_n382 (.A(FE_RN_7),
	.Y(FE_RN_116_0));
   MXI2X1 FE_RC_105_0_dup (.S0(n204),
	.B(FE_RN_191_0),
	.A(n219),
	.Y(FE_RN_6));
   NAND4X1 FE_RC_261_0 (.A(FE_RN_142_0),
	.B(FE_RN_104_0),
	.C(FE_RN_103_0),
	.D(FE_RN_102_0),
	.Y(N1894));
   CLKINVX2 FE_RC_259_0 (.A(n303),
	.Y(FE_RN_140_0));
   NAND2X1 FE_RC_258_0 (.A(A[2]),
	.B(FE_RN_18),
	.Y(FE_RN_141_0));
   CLKINVX1 FE_RC_252_0 (.A(n349),
	.Y(FE_RN_136_0));
   INVX2 FE_RC_251_0 (.A(n418),
	.Y(FE_RN_137_0));
   INVX2 FE_OFC20_n503 (.A(FE_RN_11),
	.Y(n504));
   CLKINVXL FE_RC_246_0 (.A(out_image[7]),
	.Y(FE_RN_133_0));
   CLKINVX2 FE_RC_245_0 (.A(n478),
	.Y(FE_RN_134_0));
   CLKINVX1 FE_RC_243_0 (.A(n464),
	.Y(FE_RN_130_0));
   INVX2 FE_RC_242_0 (.A(n495),
	.Y(FE_RN_131_0));
   NAND2X1 FE_RC_241_0 (.A(FE_RN_131_0),
	.B(FE_RN_130_0),
	.Y(FE_RN_132_0));
   NAND2X1 FE_RC_239_0 (.A(A[0]),
	.B(FE_RN_6),
	.Y(FE_RN_127_0));
   NOR2X1 FE_RC_238_0 (.A(n361),
	.B(FE_RN_38_0),
	.Y(FE_RN_128_0));
   NAND3X1 FE_RC_236_0 (.A(FE_RN_128_0),
	.B(FE_RN_129_0),
	.C(FE_RN_127_0),
	.Y(N1887));
   OR2X1 FE_RC_235_0 (.A(n495),
	.B(n474),
	.Y(FE_RN_126_0));
   NOR2BX1 FE_RC_143_0_dup (.AN(FE_RN_24),
	.B(FE_RN_81_0),
	.Y(FE_RN_5));
   OAI21X1 FE_RC_230_0 (.A0(FE_RN_25),
	.A1(n472),
	.B0(FE_RN_21),
	.Y(n473));
   CLKINVX2 FE_RC_229_0 (.A(FE_RN_31_0),
	.Y(FE_RN_122_0));
   NAND2X1 FE_RC_225_0 (.A(FE_RN_15),
	.B(i[5]),
	.Y(n385));
   OR2X1 FE_RC_224_0 (.A(n495),
	.B(n466),
	.Y(FE_RN_121_0));
   OR2X1 FE_RC_221_0 (.A(n495),
	.B(n477),
	.Y(FE_RN_120_0));
   OAI2BB1X1 FE_RC_217_0 (.A0N(out_image[4]),
	.A1N(n494),
	.B0(FE_RN_98_0),
	.Y(N1909));
   OR2X1 FE_RC_212_0 (.A(n495),
	.B(n485),
	.Y(FE_RN_117_0));
   OAI2BB1X1 FE_RC_211_0 (.A0N(out_image[3]),
	.A1N(n484),
	.B0(FE_RN_117_0),
	.Y(N1908));
   OAI2BB1X1 FE_RC_205_0 (.A0N(FE_OCPN45_C_out_valid),
	.A1N(FE_OFN6_n204),
	.B0(n479),
	.Y(N213));
   NOR2X1 FE_RC_201_0 (.A(n326),
	.B(FE_RN_5_0),
	.Y(FE_RN_109_0));
   OAI211X1 FE_RC_200_0 (.A0(n381),
	.A1(n508),
	.B0(n288),
	.C0(n289),
	.Y(n290));
   NAND2X1 FE_RC_195_0 (.A(n319),
	.B(n318),
	.Y(FE_RN_111_0));
   NOR2X1 FE_RC_193_0 (.A(FE_RN_111_0),
	.B(FE_RN_112_0),
	.Y(FE_RN_110_0));
   NAND2X1 FE_RC_191_0 (.A(A[9]),
	.B(n435),
	.Y(FE_RN_108_0));
   NAND3X1 FE_RC_188_0 (.A(FE_RN_110_0),
	.B(FE_RN_109_0),
	.C(FE_RN_108_0),
	.Y(N1896));
   CLKINVX2 FE_RC_186_0 (.A(n432),
	.Y(FE_RN_107_0));
   NAND2X1 FE_RC_184_0 (.A(n435),
	.B(A[8]),
	.Y(FE_RN_105_0));
   INVX2 FE_RC_182_0 (.A(n405),
	.Y(FE_RN_102_0));
   NAND2X1 FE_RC_181_0 (.A(A[7]),
	.B(n435),
	.Y(FE_RN_103_0));
   NAND2X1 FE_RC_180_0 (.A(n407),
	.B(i[7]),
	.Y(FE_RN_104_0));
   NAND3X1 FE_RC_175_0 (.A(FE_RN_101_0),
	.B(FE_RN_100_0),
	.C(FE_RN_99_0),
	.Y(N1890));
   OR2X1 FE_RC_174_0 (.A(n495),
	.B(n496),
	.Y(FE_RN_98_0));
   NAND2X1 FE_RC_172_0 (.A(n528),
	.B(block[7]),
	.Y(FE_RN_97_0));
   NAND2X1 FE_RC_171_0 (.A(FE_RN_97_0),
	.B(n211),
	.Y(n182));
   CLKINVX2 FE_RC_170_0 (.A(FE_RN_43_0),
	.Y(FE_RN_94_0));
   INVX2 FE_RC_169_0 (.A(n204),
	.Y(FE_RN_95_0));
   INVX2 FE_RC_168_0 (.A(FE_RN_96_0),
	.Y(n526));
   NAND2X1 FE_RC_164_0 (.A(n528),
	.B(block[1]),
	.Y(FE_RN_92_0));
   NAND2X1 FE_RC_163_0 (.A(n524),
	.B(FE_RN_92_0),
	.Y(n188));
   CLKINVX1 FE_RC_162_0 (.A(n439),
	.Y(FE_RN_91_0));
   MXI2X1 FE_RC_161_0 (.S0(n440),
	.B(n439),
	.A(FE_RN_91_0),
	.Y(N219));
   CLKINVX2 FE_RC_158_0 (.A(n508),
	.Y(FE_RN_90_0));
   MXI2X1 FE_RC_157_0 (.S0(n509),
	.B(n508),
	.A(FE_RN_90_0),
	.Y(N217));
   NAND2X1 FE_RC_156_0 (.A(n528),
	.B(block[5]),
	.Y(FE_RN_89_0));
   NAND2X1 FE_RC_155_0 (.A(n527),
	.B(FE_RN_89_0),
	.Y(n184));
   CLKINVX1 FE_RC_146_0 (.A(n442),
	.Y(FE_RN_82_0));
   MXI2X1 FE_RC_145_0 (.S0(n443),
	.B(n442),
	.A(FE_RN_82_0),
	.Y(N221));
   NAND2X1 FE_RC_144_0 (.A(n493),
	.B(n271),
	.Y(FE_RN_81_0));
   NOR2BX1 FE_RC_143_0 (.AN(FE_RN_24),
	.B(FE_RN_81_0),
	.Y(FE_RN_1));
   NOR3BX1 FE_RC_139_0 (.AN(n262),
	.B(n272),
	.C(n245),
	.Y(FE_RN_78_0));
   INVX2 FE_RC_138_0 (.A(FE_RN_79_0),
	.Y(n413));
   NAND2X1 FE_RC_137_0 (.A(FE_RN_24),
	.B(FE_RN_78_0),
	.Y(FE_RN_79_0));
   NAND2BX1 FE_RC_118_0 (.AN(n436),
	.B(n266),
	.Y(FE_RN_65_0));
   NAND3X1 FE_RC_117_0 (.A(n500),
	.B(FE_RN_65_0),
	.C(FE_OFN552_C_rst_n),
	.Y(n528));
   AND2X1 FE_RC_110_0 (.A(n262),
	.B(n271),
	.Y(FE_RN_61_0));
   OAI2BB1X1 FE_RC_108_0 (.A0N(i[8]),
	.A1N(n430),
	.B0(n429),
	.Y(n431));
   AND3X2 FE_RC_107_0 (.A(n513),
	.B(n262),
	.C(n282),
	.Y(FE_RN_60_0));
   NAND2X1 FE_RC_106_0 (.A(FE_RN_24),
	.B(FE_RN_60_0),
	.Y(n238));
   MXI2X1 FE_RC_105_0 (.S0(n204),
	.B(n448),
	.A(n219),
	.Y(n435));
   CLKINVX2 FE_RC_103_0 (.A(FE_RN_59_0),
	.Y(FE_RN_49_0));
   INVX2 FE_RC_97_0 (.A(FE_RN_27_0),
	.Y(FE_RN_54_0));
   NOR3X1 FE_RC_79_0 (.A(n209),
	.B(n483),
	.C(n257),
	.Y(FE_RN_43_0));
   NAND2X1 FE_RC_72_0 (.A(FE_RN_28_0),
	.B(n359),
	.Y(FE_RN_38_0));
   INVX2 FE_RC_62_0 (.A(FE_RN_24_0),
	.Y(FE_RN_33_0));
   NAND2X1 FE_RC_52_0 (.A(n448),
	.B(n202),
	.Y(FE_RN_28_0));
   CLKINVX2 FE_RC_49_0 (.A(n305),
	.Y(FE_RN_26_0));
   NOR2BX1 FE_RC_48_0 (.AN(n448),
	.B(FE_RN_26_0),
	.Y(FE_RN_27_0));
   CLKINVX2 FE_RC_44_0 (.A(n354),
	.Y(FE_RN_23_0));
   NOR2BX1 FE_RC_43_0 (.AN(n448),
	.B(FE_RN_23_0),
	.Y(FE_RN_24_0));
   CLKINVX2 FE_RC_35_0 (.A(n379),
	.Y(FE_RN_20_0));
   CLKINVX2 FE_RC_27_0 (.A(n433),
	.Y(FE_RN_15_0));
   NOR2BX1 FE_RC_26_0 (.AN(n448),
	.B(FE_RN_15_0),
	.Y(FE_RN_16_0));
   NAND2BX1 FE_RC_20_0 (.AN(n439),
	.B(n407),
	.Y(FE_RN_11_0));
   INVX2 FE_RC_19_0 (.A(A[5]),
	.Y(FE_RN_12_0));
   CLKINVX2 FE_RC_10_0 (.A(n328),
	.Y(FE_RN_4_0));
   NOR2BX1 FE_RC_9_0 (.AN(n448),
	.B(FE_RN_4_0),
	.Y(FE_RN_5_0));
   CLKINVX2 FE_RC_7_0 (.A(n292),
	.Y(FE_RN_2_0));
   INVX2 FE_OFC15_n430 (.A(n430),
	.Y(n381));
   INVX2 FE_OFC12_n204 (.A(FE_RN_25),
	.Y(FE_OFN6_n204));
   INVX2 FE_OFC5_n529 (.A(FE_RN_14),
	.Y(n500));
   BUFX2 FE_OFC2_C_rst_n (.A(FE_OFN552_C_rst_n),
	.Y(FE_OFN0_C_rst_n));
   CLKINVX2 FE_OFC1_n438 (.A(n438),
	.Y(n479));
   RA1SH mem (.Q(Q),
	.CLK(CTS_4),
	.CEN(1'b0),
	.OEN(1'b0),
	.WEN(write_en),
	.A({ A[9],
		A[8],
		A[7],
		A[6],
		A[5],
		A[4],
		A[3],
		A[2],
		n199,
		A[0] }),
	.D(D));
   DFFXL block_reg_4_ (.D(n185),
	.CK(CTS_4),
	.Q(block[4]),
	.QN(n545));
   DFFXL block_reg_2_ (.D(n187),
	.CK(CTS_4),
	.Q(block[2]),
	.QN(n543));
   DFFXL block_reg_1_ (.D(n188),
	.CK(CTS_4),
	.Q(block[1]),
	.QN(n542));
   DFFXL block_reg_3_ (.D(n186),
	.CK(CTS_4),
	.Q(block[3]),
	.QN(n544));
   DFFRHQXL D_reg_7_ (.D(N233),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(D[7]));
   DFFRHQXL D_reg_6_ (.D(N232),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(D[6]));
   DFFRHQXL D_reg_5_ (.D(N231),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(D[5]));
   DFFRHQXL D_reg_4_ (.D(N230),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(D[4]));
   DFFRHQXL D_reg_3_ (.D(N229),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(D[3]));
   DFFRHQXL D_reg_2_ (.D(N228),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(D[2]));
   DFFRHQXL D_reg_1_ (.D(N227),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(D[1]));
   DFFRHQXL D_reg_0_ (.D(N226),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(D[0]));
   DFFRHQXL center_reg_0_ (.D(N1897),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[0]));
   DFFRHQXL center_reg_5_ (.D(N1902),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[5]));
   DFFRHQXL center_reg_2_ (.D(N1899),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[2]));
   DFFRHQXL center_reg_6_ (.D(N1903),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(center[6]));
   DFFRHQXL center_reg_4_ (.D(N1901),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[4]));
   DFFRHQXL center_reg_1_ (.D(N1898),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[1]));
   DFFRHQXL center_reg_7_ (.D(N1904),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(center[7]));
   DFFRHQXL center_reg_3_ (.D(N1900),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[3]));
   DFFRHQX4 out_image_reg_7_ (.D(N1912),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(FE_RN_28));
   DFFRHQX4 out_image_reg_6_ (.D(N1911),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(out_image[6]));
   DFFRHQX4 out_image_reg_5_ (.D(N1910),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(out_image[5]));
   DFFRHQX4 out_image_reg_4_ (.D(N1909),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(out_image[4]));
   DFFRHQX4 out_image_reg_3_ (.D(N1908),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(FE_RN_30));
   DFFRHQX4 out_image_reg_2_ (.D(N1907),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(FE_OCPN551_C_out_image_2));
   DFFRHQX4 out_image_reg_1_ (.D(N1906),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(FE_OCPN550_C_out_image_1));
   DFFRHQX4 out_image_reg_0_ (.D(N1905),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(FE_OCPN549_C_out_image_0));
   DFFRHQXL i_reg_2_ (.D(N216),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(C1_DATA6_2));
   DFFRHQXL finish_all_reg (.D(N212),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(finish_all));
   DFFRHQXL counter_block_reg_3_ (.D(N172),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(counter_block[3]));
   DFFRHQXL i_reg_7_ (.D(N221),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(i[7]));
   DFFRHQXL i_reg_3_ (.D(N217),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(C1_DATA6_3));
   DFFRHQXL i_reg_9_ (.D(N223),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(i[9]));
   DFFRHQX1 i_reg_0_ (.D(N214),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(C1_DATA6_0));
   DFFRHQXL i_reg_4_ (.D(N218),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(C1_DATA6_4));
   DFFRHQXL i_reg_1_ (.D(N215),
	.CK(CTS_4),
	.RN(FE_OFN0_C_rst_n),
	.Q(C1_DATA6_1));
   DFFRHQX4 out_valid_reg (.D(N213),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(FE_OCPN548_C_out_valid));
   DFFRHQX1 counter_block_reg_0_ (.D(n548),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(counter_block[0]));
   DFFRHQXL i_reg_8_ (.D(N222),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(i[8]));
   DFFRHQXL counter_block_reg_2_ (.D(N171),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(counter_block[2]));
   DFFHQXL block_reg_5_ (.D(n184),
	.CK(CTS_4),
	.Q(block[5]));
   DFFRX1 state_reg_1_ (.D(next_state[1]),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(state[1]),
	.QN(n535));
   DFFXL block_reg_6_ (.D(n183),
	.CK(CTS_4),
	.Q(block[6]),
	.QN(n546));
   DFFXL block_reg_0_ (.D(n189),
	.CK(CTS_4),
	.Q(block[0]),
	.QN(n541));
   DFFXL block_reg_7_ (.D(n182),
	.CK(CTS_4),
	.Q(block[7]),
	.QN(n547));
   DFFRX1 state_reg_0_ (.D(next_state[0]),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(state[0]),
	.QN(n536));
   DFFSXL write_en_reg (.D(FE_RN_21),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(write_en));
   DFFSXL A_reg_0_ (.D(N1887),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[0]),
	.QN(n202));
   DFFSXL A_reg_2_ (.D(N1889),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[2]),
	.QN(n201));
   DFFSXL A_reg_1_ (.D(N1888),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(n199),
	.QN(n532));
   DFFSXL A_reg_6_ (.D(N1893),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[6]),
	.QN(n540));
   DFFSXL A_reg_4_ (.D(N1891),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[4]),
	.QN(n538));
   DFFSXL A_reg_8_ (.D(N1895),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[8]));
   DFFSXL A_reg_9_ (.D(N1896),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[9]));
   DFFSXL A_reg_3_ (.D(N1890),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[3]),
	.QN(n200));
   DFFSXL A_reg_5_ (.D(N1892),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[5]),
	.QN(n539));
   DFFSXL A_reg_7_ (.D(N1894),
	.CK(CTS_4),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[7]));
   DFFRHQXL counter_block_reg_1_ (.D(N170),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(counter_block[1]));
   DFFRHQXL i_reg_5_ (.D(N219),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(i[5]));
   DFFRHQXL i_reg_6_ (.D(N220),
	.CK(CTS_4),
	.RN(FE_OFN552_C_rst_n),
	.Q(i[6]));
   NOR2X2 U256 (.A(FE_RN_25),
	.B(n511),
	.Y(n438));
   NOR2X1 U259 (.A(n332),
	.B(n441),
	.Y(n486));
   AND2XL U260 (.A(n276),
	.B(n277),
	.Y(n278));
   NOR2X1 U262 (.A(n496),
	.B(n252),
	.Y(n253));
   NOR2X1 U263 (.A(C1_DATA6_2),
	.B(C1_DATA6_3),
	.Y(n368));
   NOR2X1 U264 (.A(C1_DATA6_0),
	.B(C1_DATA6_1),
	.Y(n369));
   NOR2X1 U265 (.A(n223),
	.B(n235),
	.Y(n513));
   NOR2X1 U266 (.A(n467),
	.B(counter_block[1]),
	.Y(n234));
   NOR2X1 U267 (.A(C1_DATA6_1),
	.B(C1_DATA6_2),
	.Y(n232));
   NOR2X1 U268 (.A(n506),
	.B(n226),
	.Y(n227));
   AOI2BB1XL U277 (.A0N(n262),
	.A1N(n249),
	.B0(n483),
	.Y(n250));
   XOR2XL U279 (.A(n280),
	.B(n200),
	.Y(n281));
   XNOR2XL U280 (.A(n294),
	.B(n201),
	.Y(n305));
   NOR2X1 U281 (.A(n296),
	.B(C1_DATA6_2),
	.Y(n240));
   INVX2 U282 (.A(n235),
	.Y(n265));
   NAND2X1 U283 (.A(n203),
	.B(state[1]),
	.Y(n216));
   CLKINVX2 U284 (.A(n214),
	.Y(n436));
   NAND2XL U285 (.A(C1_DATA6_3),
	.B(C1_DATA6_4),
	.Y(n226));
   AOI22X1 U287 (.A0(FE_RN_26),
	.A1(C1_DATA6_0),
	.B0(n413),
	.B1(n356),
	.Y(n358));
   NAND2X1 U288 (.A(n381),
	.B(FE_RN_7),
	.Y(n407));
   NAND2X1 U289 (.A(n493),
	.B(n227),
	.Y(n260));
   NOR2X1 U291 (.A(n531),
	.B(counter_block[2]),
	.Y(n437));
   INVXL U296 (.A(n262),
	.Y(n270));
   NAND2XL U297 (.A(i[5]),
	.B(i[6]),
	.Y(n310));
   XNOR2XL U298 (.A(i[9]),
	.B(n313),
	.Y(n323));
   OR2XL U299 (.A(n412),
	.B(i[8]),
	.Y(n313));
   NAND2X1 U300 (.A(FE_RN_24),
	.B(n236),
	.Y(n237));
   NOR4XL U301 (.A(n270),
	.B(n264),
	.C(n245),
	.D(n235),
	.Y(n236));
   AND2X1 U302 (.A(FE_RN_24),
	.B(n253),
	.Y(n418));
   AND2X1 U303 (.A(FE_RN_24),
	.B(n244),
	.Y(n414));
   AOI2BB1X1 U304 (.A0N(n243),
	.A1N(n242),
	.B0(n272),
	.Y(n244));
   AOI21XL U305 (.A0(n241),
	.A1(counter_block[0]),
	.B0(n481),
	.Y(n243));
   OR2X1 U308 (.A(FE_RN_25),
	.B(n480),
	.Y(n495));
   INVXL U309 (.A(n369),
	.Y(n296));
   NAND4X1 U310 (.A(n232),
	.B(n356),
	.C(n508),
	.D(n447),
	.Y(n262));
   NAND4XL U311 (.A(n220),
	.B(n442),
	.C(n488),
	.D(n439),
	.Y(n264));
   NAND2X1 U312 (.A(n264),
	.B(n265),
	.Y(n272));
   NAND2X1 U313 (.A(C1_DATA6_1),
	.B(C1_DATA6_0),
	.Y(n365));
   INVXL U314 (.A(n365),
	.Y(n295));
   XOR2XL U315 (.A(n506),
	.B(n508),
	.Y(n292));
   NAND2X1 U317 (.A(FE_RN_23),
	.B(n287),
	.Y(n256));
   AOI22X1 U320 (.A0(n284),
	.A1(n324),
	.B0(n427),
	.B1(n323),
	.Y(n325));
   NAND2XL U324 (.A(n227),
	.B(n257),
	.Y(n258));
   OAI31X1 U328 (.A0(counter_block[1]),
	.A1(counter_block[2]),
	.A2(counter_block[0]),
	.B0(counter_block[3]),
	.Y(n219));
   NAND3BXL U329 (.AN(state[0]),
	.B(out_valid),
	.C(finish_all),
	.Y(n203));
   AOI21XL U330 (.A0(n227),
	.A1(i[5]),
	.B0(i[6]),
	.Y(n332));
   XOR2XL U331 (.A(n410),
	.B(i[8]),
	.Y(n518));
   INVXL U332 (.A(C1_DATA6_4),
	.Y(n447));
   NAND2X1 U333 (.A(n438),
	.B(C1_DATA6_0),
	.Y(n503));
   XOR2XL U334 (.A(n312),
	.B(n499),
	.Y(n497));
   NAND2XL U335 (.A(n410),
	.B(i[8]),
	.Y(n312));
   INVX2 U336 (.A(C1_DATA6_3),
	.Y(n508));
   INVXL U337 (.A(n331),
	.Y(n441));
   NAND2XL U339 (.A(n206),
	.B(counter_block[3]),
	.Y(n207));
   NAND2XL U340 (.A(n214),
	.B(n205),
	.Y(n206));
   INVXL U341 (.A(n231),
	.Y(n223));
   NAND2X1 U342 (.A(n437),
	.B(n233),
	.Y(n468));
   NAND2X1 U343 (.A(FE_RN_24),
	.B(n265),
	.Y(n204));
   NAND2XL U345 (.A(n437),
	.B(n436),
	.Y(n511));
   OAI22XL U346 (.A0(n462),
	.A1(n461),
	.B0(block[7]),
	.B1(n460),
	.Y(n480));
   OAI22XL U347 (.A0(center[7]),
	.A1(n547),
	.B0(center[6]),
	.B1(n546),
	.Y(n461));
   AOI21XL U348 (.A0(n459),
	.A1(n458),
	.B0(n457),
	.Y(n462));
   OR2XL U349 (.A(i[5]),
	.B(i[6]),
	.Y(n392));
   OR2XL U350 (.A(n392),
	.B(i[7]),
	.Y(n412));
   INVX2 U352 (.A(n271),
	.Y(n252));
   NAND2XL U353 (.A(n266),
	.B(n234),
	.Y(n245));
   NAND2XL U354 (.A(n266),
	.B(n436),
	.Y(n285));
   AND2XL U355 (.A(n396),
	.B(i[7]),
	.Y(n416));
   XNOR2XL U356 (.A(i[8]),
	.B(n412),
	.Y(n426));
   AND2XL U357 (.A(n369),
	.B(n368),
	.Y(n370));
   NAND4XL U359 (.A(n267),
	.B(n266),
	.C(n467),
	.D(n265),
	.Y(n268));
   NAND2XL U360 (.A(n263),
	.B(n513),
	.Y(n269));
   OAI2BB1X1 U361 (.A0N(n275),
	.A1N(n274),
	.B0(FE_RN_24),
	.Y(n276));
   NAND3XL U362 (.A(n273),
	.B(n475),
	.C(n227),
	.Y(n274));
   NAND3XL U363 (.A(n271),
	.B(n472),
	.C(n270),
	.Y(n275));
   NAND2XL U367 (.A(n227),
	.B(n311),
	.Y(n331));
   INVXL U368 (.A(n310),
	.Y(n311));
   NAND3XL U369 (.A(i[7]),
	.B(i[8]),
	.C(i[9]),
	.Y(n222));
   NOR3BXL U370 (.AN(counter_block[2]),
	.B(counter_block[3]),
	.C(counter_block[0]),
	.Y(n282));
   OAI2BB1XL U371 (.A0N(n455),
	.A1N(n454),
	.B0(n453),
	.Y(n459));
   AOI22XL U372 (.A0(center[3]),
	.A1(n544),
	.B0(n545),
	.B1(center[4]),
	.Y(n453));
   AOI2BB2XL U373 (.A0N(center[2]),
	.A1N(n543),
	.B0(n449),
	.B1(block[3]),
	.Y(n455));
   OAI211XL U374 (.A0(block[1]),
	.A1(n452),
	.B0(n451),
	.C0(n450),
	.Y(n454));
   AOI2BB2XL U375 (.A0N(center[4]),
	.A1N(n545),
	.B0(n456),
	.B1(block[5]),
	.Y(n458));
   OAI2BB2XL U376 (.A0N(center[6]),
	.A1N(n546),
	.B0(n456),
	.B1(block[5]),
	.Y(n457));
   NAND2XL U377 (.A(n266),
	.B(counter_block[1]),
	.Y(n481));
   INVXL U378 (.A(n282),
	.Y(n261));
   NAND2XL U379 (.A(n285),
	.B(n477),
	.Y(n257));
   NAND2X1 U385 (.A(FE_RN_116_0),
	.B(n518),
	.Y(n424));
   AOI22X1 U388 (.A0(n284),
	.A1(n428),
	.B0(n427),
	.B1(n426),
	.Y(n429));
   NAND2X1 U396 (.A(FE_RN_116_0),
	.B(n349),
	.Y(n348));
   AOI22X1 U397 (.A0(n284),
	.A1(n301),
	.B0(n427),
	.B1(n489),
	.Y(n302));
   NAND2X1 U400 (.A(FE_RN_116_0),
	.B(n489),
	.Y(n300));
   NAND2XL U401 (.A(counter_block[0]),
	.B(counter_block[1]),
	.Y(n214));
   INVX2 U402 (.A(i[5]),
	.Y(n439));
   XOR2XL U403 (.A(n367),
	.B(n447),
	.Y(n445));
   OR2XL U404 (.A(n366),
	.B(n365),
	.Y(n367));
   INVXL U405 (.A(i[9]),
	.Y(n499));
   INVXL U406 (.A(i[7]),
	.Y(n442));
   NAND2XL U407 (.A(n436),
	.B(counter_block[2]),
	.Y(n530));
   XNOR2X1 U408 (.A(n295),
	.B(n491),
	.Y(n489));
   NAND2BX1 U409 (.AN(n261),
	.B(n233),
	.Y(n474));
   NAND4BX1 U410 (.AN(counter_block[3]),
	.B(n233),
	.C(counter_block[2]),
	.D(counter_block[0]),
	.Y(n477));
   NAND2XL U411 (.A(n282),
	.B(counter_block[1]),
	.Y(n466));
   INVXL U412 (.A(n483),
	.Y(n485));
   NOR2X1 U413 (.A(n468),
	.B(counter_block[0]),
	.Y(n493));
   INVX2 U414 (.A(n493),
	.Y(n496));
   NAND3XL U415 (.A(n437),
	.B(counter_block[1]),
	.C(n467),
	.Y(n464));
   NAND3XL U416 (.A(n261),
	.B(n468),
	.C(n464),
	.Y(n209));
   AND2X1 U419 (.A(n448),
	.B(n388),
	.Y(n389));
   OAI2BB1X1 U424 (.A0N(i[9]),
	.A1N(n430),
	.B0(n325),
	.Y(n326));
   MXI2X1 U430 (.S0(state[1]),
	.B(n217),
	.A(n218),
	.Y(next_state[0]));
   NAND3BXL U431 (.AN(finish_all),
	.B(n536),
	.C(out_valid),
	.Y(n217));
   INVX1 U432 (.A(in_valid),
	.Y(n218));
   NAND2X1 U434 (.A(Q[7]),
	.B(n526),
	.Y(n211));
   OAI2BB1X1 U435 (.A0N(n528),
	.A1N(block[0]),
	.B0(n213),
	.Y(n189));
   NAND2X1 U436 (.A(Q[0]),
	.B(n526),
	.Y(n213));
   OAI2BB1X1 U437 (.A0N(n528),
	.A1N(block[6]),
	.B0(n212),
	.Y(n183));
   NAND2X1 U438 (.A(Q[6]),
	.B(n526),
	.Y(n212));
   OAI21X1 U439 (.A0(in_valid),
	.A1(n536),
	.B0(n216),
	.Y(next_state[1]));
   NAND2X1 U441 (.A(n526),
	.B(Q[5]),
	.Y(n527));
   MXI2X1 U442 (.S0(n438),
	.B(n487),
	.A(n488),
	.Y(N220));
   NAND2X1 U444 (.A(n438),
	.B(n227),
	.Y(n440));
   MXI2X1 U445 (.S0(n438),
	.B(n520),
	.A(n521),
	.Y(N222));
   INVXL U446 (.A(n518),
	.Y(n520));
   NAND2X1 U448 (.A(n500),
	.B(counter_block[0]),
	.Y(n502));
   MXI2X1 U451 (.S0(n438),
	.B(n446),
	.A(n447),
	.Y(N218));
   INVXL U452 (.A(n445),
	.Y(n446));
   MXI2X1 U454 (.S0(n438),
	.B(n498),
	.A(n499),
	.Y(N223));
   INVXL U455 (.A(n497),
	.Y(n498));
   NAND2X1 U457 (.A(n438),
	.B(n507),
	.Y(n509));
   NAND2X1 U459 (.A(n438),
	.B(n441),
	.Y(n443));
   AOI21XL U460 (.A0(n531),
	.A1(n530),
	.B0(FE_RN_14),
	.Y(N172));
   NAND2XL U461 (.A(n517),
	.B(n516),
	.Y(N212));
   NAND4XL U462 (.A(FE_RN_24),
	.B(n227),
	.C(n513),
	.D(n512),
	.Y(n516));
   NAND3XL U463 (.A(FE_OFN6_n204),
	.B(finish_all),
	.C(n511),
	.Y(n517));
   MXI2X1 U464 (.S0(n438),
	.B(n490),
	.A(n491),
	.Y(N216));
   INVXL U465 (.A(n489),
	.Y(n490));
   OAI2BB1X1 U471 (.A0N(n466),
	.A1N(FE_OFN6_n204),
	.B0(FE_RN_21),
	.Y(n465));
   OAI21X1 U477 (.A0(n469),
	.A1(FE_RN_25),
	.B0(FE_RN_21),
	.Y(n470));
   OAI2BB1X1 U481 (.A0N(n511),
	.A1N(FE_OFN6_n204),
	.B0(FE_RN_21),
	.Y(n478));
   AND2X1 U482 (.A(n448),
	.B(in_image[0]),
	.Y(N226));
   AND2X1 U483 (.A(n448),
	.B(in_image[1]),
	.Y(N227));
   AND2XL U484 (.A(FE_OCPN35_n448),
	.B(in_image[2]),
	.Y(N228));
   AND2XL U485 (.A(FE_OCPN42_n448),
	.B(in_image[3]),
	.Y(N229));
   AND2XL U486 (.A(FE_OCPN42_n448),
	.B(in_image[4]),
	.Y(N230));
   AND2X1 U487 (.A(n448),
	.B(in_image[5]),
	.Y(N231));
   AND2X1 U488 (.A(n448),
	.B(in_image[6]),
	.Y(N232));
   AND2X1 U489 (.A(n448),
	.B(in_image[7]),
	.Y(N233));
   OAI2BB1X1 U490 (.A0N(block[3]),
	.A1N(n528),
	.B0(n525),
	.Y(n186));
   NAND2X1 U491 (.A(Q[3]),
	.B(n526),
	.Y(n525));
   NAND2X1 U493 (.A(Q[1]),
	.B(n526),
	.Y(n524));
   OAI2BB1X1 U494 (.A0N(block[2]),
	.A1N(n528),
	.B0(n522),
	.Y(n187));
   NAND2X1 U495 (.A(Q[2]),
	.B(n526),
	.Y(n522));
   OAI2BB1X1 U496 (.A0N(block[4]),
	.A1N(n528),
	.B0(n523),
	.Y(n185));
   NAND2X1 U497 (.A(Q[4]),
	.B(n526),
	.Y(n523));
   INVXL U498 (.A(C1_DATA6_2),
	.Y(n491));
   NOR2X1 U501 (.A(counter_block[3]),
	.B(counter_block[2]),
	.Y(n266));
   AOI2BB1X1 U503 (.A0N(n535),
	.A1N(FE_OCPN45_C_out_valid),
	.B0(state[0]),
	.Y(n235));
   INVXL U504 (.A(counter_block[2]),
	.Y(n205));
   NOR2X1 U506 (.A(n530),
	.B(counter_block[3]),
	.Y(n483));
   INVXL U507 (.A(counter_block[1]),
	.Y(n233));
   INVXL U508 (.A(counter_block[3]),
	.Y(n531));
   INVXL U509 (.A(counter_block[0]),
	.Y(n467));
   XOR2XL U510 (.A(n214),
	.B(counter_block[2]),
	.Y(n215));
   NOR2X1 U511 (.A(FE_RN_14),
	.B(n215),
	.Y(N171));
   NAND2X1 U512 (.A(n295),
	.B(C1_DATA6_2),
	.Y(n506));
   NOR2X1 U513 (.A(i[8]),
	.B(i[9]),
	.Y(n220));
   INVX2 U514 (.A(i[6]),
	.Y(n488));
   NOR2X1 U515 (.A(n264),
	.B(n235),
	.Y(n221));
   NOR2X1 U517 (.A(n222),
	.B(n310),
	.Y(n231));
   NOR2X1 U518 (.A(n227),
	.B(n272),
	.Y(n228));
   NOR2X1 U520 (.A(n231),
	.B(n235),
	.Y(n271));
   INVX2 U521 (.A(C1_DATA6_0),
	.Y(n356));
   XOR2XL U524 (.A(n240),
	.B(C1_DATA6_3),
	.Y(n287));
   INVXL U525 (.A(n227),
	.Y(n241));
   NOR2X1 U526 (.A(n262),
	.B(n245),
	.Y(n242));
   AOI22X1 U530 (.A0(FE_RN_26),
	.A1(C1_DATA6_3),
	.B0(n413),
	.B1(n287),
	.Y(n255));
   NAND3XL U531 (.A(n531),
	.B(counter_block[2]),
	.C(counter_block[1]),
	.Y(n249));
   AOI21X1 U532 (.A0(n250),
	.A1(n260),
	.B0(n252),
	.Y(n251));
   OAI211XL U536 (.A0(n262),
	.A1(n261),
	.B0(n260),
	.C0(n485),
	.Y(n263));
   NAND2XL U537 (.A(n264),
	.B(counter_block[1]),
	.Y(n267));
   INVXL U538 (.A(n474),
	.Y(n472));
   INVXL U539 (.A(n272),
	.Y(n273));
   INVXL U540 (.A(n477),
	.Y(n475));
   NAND2X1 U542 (.A(n199),
	.B(A[0]),
	.Y(n307));
   INVXL U543 (.A(n307),
	.Y(n294));
   NAND2XL U544 (.A(n294),
	.B(A[2]),
	.Y(n280));
   NAND2X1 U545 (.A(n448),
	.B(n281),
	.Y(n289));
   XNOR2XL U548 (.A(n296),
	.B(C1_DATA6_2),
	.Y(n301));
   NAND2X1 U549 (.A(FE_RN_15),
	.B(n301),
	.Y(n299));
   OAI2BB1X1 U551 (.A0N(C1_DATA6_2),
	.A1N(n430),
	.B0(n302),
	.Y(n303));
   NAND2X1 U553 (.A(A[2]),
	.B(A[3]),
	.Y(n308));
   NOR2X1 U554 (.A(n308),
	.B(n307),
	.Y(n364));
   NAND2X1 U555 (.A(n364),
	.B(A[4]),
	.Y(n387));
   NOR2X1 U556 (.A(n387),
	.B(n539),
	.Y(n330));
   AND2X1 U557 (.A(n330),
	.B(A[6]),
	.Y(n403));
   XOR2X1 U558 (.A(n309),
	.B(A[9]),
	.Y(n328));
   NOR2X1 U559 (.A(n331),
	.B(n442),
	.Y(n410));
   XOR2XL U561 (.A(n314),
	.B(i[9]),
	.Y(n317));
   NOR2X1 U562 (.A(n439),
	.B(n488),
	.Y(n396));
   XOR2XL U563 (.A(n315),
	.B(i[9]),
	.Y(n316));
   XOR2XL U565 (.A(n322),
	.B(i[9]),
	.Y(n324));
   XNOR2XL U568 (.A(i[6]),
	.B(i[5]),
	.Y(n338));
   ADDHXL U569 (.A(i[6]),
	.B(i[5]),
	.S(n333),
	.CO(n395));
   XOR2XL U570 (.A(n439),
	.B(n488),
	.Y(n339));
   XNOR2XL U573 (.A(n532),
	.B(A[0]),
	.Y(n354));
   XOR2XL U574 (.A(C1_DATA6_0),
	.B(C1_DATA6_1),
	.Y(n349));
   XNOR2X1 U575 (.A(C1_DATA6_1),
	.B(C1_DATA6_0),
	.Y(n350));
   NAND2X1 U576 (.A(FE_RN_15),
	.B(n350),
	.Y(n347));
   NAND2X1 U582 (.A(FE_RN_23),
	.B(n356),
	.Y(n360));
   XNOR2X1 U585 (.A(n364),
	.B(n538),
	.Y(n379));
   NAND2XL U586 (.A(C1_DATA6_2),
	.B(C1_DATA6_3),
	.Y(n366));
   XOR2XL U587 (.A(n370),
	.B(C1_DATA6_4),
	.Y(n375));
   AOI22X1 U593 (.A0(n284),
	.A1(n439),
	.B0(n427),
	.B1(n439),
	.Y(n386));
   XOR2X1 U595 (.A(n387),
	.B(n539),
	.Y(n388));
   ADDHXL U596 (.A(i[7]),
	.B(n396),
	.S(n393),
	.CO(n425));
   XNOR2XL U597 (.A(n392),
	.B(i[7]),
	.Y(n394));
   NAND2X1 U598 (.A(FE_RN_15),
	.B(i[7]),
	.Y(n401));
   ADDHXL U599 (.A(i[7]),
	.B(n395),
	.S(n398),
	.CO(n415));
   XNOR2XL U600 (.A(n396),
	.B(n442),
	.Y(n397));
   ADDHXL U602 (.A(A[7]),
	.B(n403),
	.S(n404),
	.CO(n409));
   AND2X1 U603 (.A(n448),
	.B(n404),
	.Y(n405));
   ADDHXL U605 (.A(A[8]),
	.B(n409),
	.S(n433),
	.CO(n309));
   NAND2X1 U606 (.A(FE_RN_23),
	.B(i[8]),
	.Y(n423));
   ADDHXL U607 (.A(i[8]),
	.B(n415),
	.S(n419),
	.CO(n314));
   ADDHXL U608 (.A(i[8]),
	.B(n416),
	.S(n417),
	.CO(n315));
   ADDHXL U610 (.A(i[8]),
	.B(n425),
	.S(n428),
	.CO(n322));
   INVXL U613 (.A(C1_DATA6_1),
	.Y(n444));
   INVXL U614 (.A(center[3]),
	.Y(n449));
   INVXL U615 (.A(center[1]),
	.Y(n452));
   OAI211XL U616 (.A0(center[1]),
	.A1(n542),
	.B0(center[0]),
	.C0(n541),
	.Y(n451));
   NAND2XL U617 (.A(n543),
	.B(center[2]),
	.Y(n450));
   INVXL U618 (.A(center[5]),
	.Y(n456));
   INVXL U619 (.A(center[7]),
	.Y(n460));
   NOR2X1 U620 (.A(n468),
	.B(n467),
	.Y(n469));
   INVXL U621 (.A(n469),
	.Y(n471));
   MX2X2 U623 (.S0(FE_RN_22),
	.B(Q[0]),
	.A(center[0]),
	.Y(N1897));
   MX2X2 U624 (.S0(FE_RN_22),
	.B(Q[2]),
	.A(center[2]),
	.Y(N1899));
   MX2X2 U625 (.S0(n482),
	.B(Q[6]),
	.A(center[6]),
	.Y(N1903));
   MX2X2 U626 (.S0(FE_RN_19),
	.B(Q[4]),
	.A(center[4]),
	.Y(N1901));
   MX2X2 U627 (.S0(n482),
	.B(Q[5]),
	.A(center[5]),
	.Y(N1902));
   MX2X2 U628 (.S0(FE_RN_22),
	.B(Q[1]),
	.A(center[1]),
	.Y(N1898));
   MX2X2 U629 (.S0(n482),
	.B(Q[7]),
	.A(center[7]),
	.Y(N1904));
   MX2X2 U630 (.S0(FE_RN_22),
	.B(Q[3]),
	.A(center[3]),
	.Y(N1900));
   INVXL U631 (.A(n486),
	.Y(n487));
   INVXL U634 (.A(n506),
	.Y(n507));
   INVXL U635 (.A(n511),
	.Y(n512));
   INVXL U636 (.A(i[8]),
	.Y(n521));
endmodule

module CHIP (
	clk, 
	rst_n, 
	in_valid, 
	in_image, 
	out_valid, 
	out_image);
   input clk;
   input rst_n;
   input in_valid;
   input [7:0] in_image;
   output out_valid;
   output [7:0] out_image;

   // Internal wires
   wire C_clk;
   wire C_rst_n;
   wire C_in_valid;
   wire [7:0] C_in_image;
   wire C_out_valid;
   wire [7:0] C_out_image;

   LBP LBP (.clk(C_clk),
	.rst_n(C_rst_n),
	.in_valid(C_in_valid),
	.in_image(C_in_image),
	.out_valid(C_out_valid),
	.out_image(C_out_image));
   P8C I_CLK (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b0),
	.CSEN(1'b1),
	.Y(C_clk),
	.P(clk));
   P8C I_RESET (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_rst_n),
	.P(rst_n));
   P4C I_VALID (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_valid),
	.P(in_valid));
   P4C I_IN_0 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[0]),
	.P(in_image[0]));
   P4C I_IN_1 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[1]),
	.P(in_image[1]));
   P4C I_IN_2 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[2]),
	.P(in_image[2]));
   P4C I_IN_3 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[3]),
	.P(in_image[3]));
   P4C I_IN_4 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[4]),
	.P(in_image[4]));
   P4C I_IN_5 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[5]),
	.P(in_image[5]));
   P4C I_IN_6 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[6]),
	.P(in_image[6]));
   P4C I_IN_7 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[7]),
	.P(in_image[7]));
   P8C O_VALID (.A(C_out_valid),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_valid));
   P8C O_OUT_0 (.A(C_out_image[0]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[0]));
   P8C O_OUT_1 (.A(C_out_image[1]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[1]));
   P8C O_OUT_2 (.A(C_out_image[2]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[2]));
   P8C O_OUT_3 (.A(C_out_image[3]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[3]));
   P8C O_OUT_4 (.A(C_out_image[4]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[4]));
   P8C O_OUT_5 (.A(C_out_image[5]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[5]));
   P8C O_OUT_6 (.A(C_out_image[6]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[6]));
   P8C O_OUT_7 (.A(C_out_image[7]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[7]));
   PVDDR VDDP0 ();
   PVSSR GNDP0 ();
   PVDDR VDDP1 ();
   PVSSR GNDP1 ();
   PVDDR VDDP2 ();
   PVSSR GNDP2 ();
   PVDDR VDDP3 ();
   PVSSR GNDP3 ();
   PVDDC VDDC0 ();
   PVSSC GNDC0 ();
   PVDDC VDDC1 ();
   PVSSC GNDC1 ();
   PVDDC VDDC2 ();
   PVSSC GNDC2 ();
   PVDDC VDDC3 ();
   PVSSC GNDC3 ();
endmodule

